### ISSUE TITLE
Initial users setup

### ISSUE THREAD

**Issue by L-B** [severalnines/ansible-clustercontrol#2]
Hello,

This method says to create a user account manually after the playbook has been run.
I would be interested in a way to automatically set-up an initial user, or better yet, configure the LDAP connection itself to the AD, so that ClusterControl is directly usable.

Thanks in advance.

**Comment by ashraf-s9s** [comment]
Hi @L-B , this is now supported as shown in the example playbook:
https://github.com/severalnines/ansible-clustercontrol/blob/master/examples/example-playbook.yml 

I'm closing this issue.
