### ISSUE TITLE
deprecated option - innodb_additional_mem_pool_size

### ISSUE THREAD

**Issue by JanReiners** [severalnines/ansible-clustercontrol#5]
System: CentOS 7
MariaDB-Version: 10.2
Tags: controller

Error:
configure-mysql.yml:12
"Unable to start service mariadb"
error.log:
[ERROR] /usr/sbin/mysqld: unknown variable 'innodb_additional_mem_pool_size=20M'

Reason:
https://mariadb.com/kb/en/library/upgrading-from-mariadb-101-to-mariadb-102/#options-that-have-been-removed-or-renamed

**Comment by freddielunchbird** [comment]
Hi,
Many thanks for this.
I have removed the innodb_additional_mem_pool_size altogether as it is deprecated also in MySQL 5.6 and onwards.

Best regards
Johan

**Comment by ashraf-s9s** [comment]
Hi @JanReiners 

Closing this issue based on this fix:
https://github.com/severalnines/ansible-clustercontrol/commit/95eb9c1f0fd65631ff5629436ec0b6a329f55625
