### ISSUE TITLE
mariadb

### ISSUE THREAD

**Issue by churnd** [severalnines/ansible-clustercontrol#8]
I notice the playbook doesn't work well when setting up a controller to use mariadb instead of mysql on Debian 10, as it expects packages named mysql-*, when Debian 10 seems to be shifting the default packages to mariadb.  I'm not sure how much work it would be to add support for either mysql-* packages or mariadb-* packages?

**Comment by ashraf-s9s** [comment]
Hi @churnd , 

We are currently updating the Ansible playbook to support Debian 10, Ubuntu 18.04 and CentOS 8. I'll let you know when it's ready.

**Comment by ashraf-s9s** [comment]
Hi @churnd 

We have just updated and published ClusterControl 1.7.5 playbook which support Debian 10 and RHEL 8 deployment. It is now available at [Ansible Galaxy](https://galaxy.ansible.com/severalnines/clustercontrol). 

Therefore, I'm going to close this issue.
